---
title: "Loops and Iterative Practice"
author: "Sandy Illescas"
date: "2023-04-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set( echo = TRUE,
  fig.path = "../Output/",
	message = FALSE,
	warning = FALSE)
```

# Load Libraries
```{r}

library(tidyverse)
library(here)

```


```{r}
print(paste("The year is", 2000))
```
```{r}
years<-c(2015:2021) # this tells r what values to loop over, this must be in sequence. 
for (i in years){ # set up the for loop where i is the index
  print(paste("The year is", i)) # loop over i
}
```
```{r}
#Pre-allocate space for the for loop
# empty matrix
year_data<-data.frame(matrix(ncol = 2, nrow = length(years)))
# add column names
colnames(year_data)<-c("year", "year_name")
year_data
```

```{r}
for (i in 1:length(years)){ # set up the for loop where i is the index
  year_data$year_name[i]<-paste("The year is", years[i]) # loop over i
}
year_data
```

```{r}
for (i in 1:length(years)){ # set up the for loop where i is the index
  year_data$year_name[i]<-paste("The year is", years[i]) # loop over year name
  year_data$year[i]<-years[i] # loop over year
}
year_data
```
```{r}
testdata<-read_csv(here("Week_12", "Data", "cond_data","011521_CT316_1pcal.csv"))
glimpse(testdata)
```

```{r}
# point to the location on the computer of the folder
CondPath<-here("Week_12", "data", "cond_data")
# list all the files in that path with a specific pattern
# In this case we are looking for everything that has a .csv in the filename
# you can use regex to be more specific if you are looking for certain patterns in filenames
files <- dir(path = CondPath,pattern = ".csv")
files
```
```{r}
# pre-allocate space
# make an empty dataframe that has one row for each file and 3 columns
cond_data<-data.frame(matrix(nrow = length(files), ncol = 3))
# give the dataframe column names
colnames(cond_data)<-c("filename","mean_temp", "mean_sal")
cond_data
```

```{r}
raw_data<-read_csv(paste0(CondPath,"/",files[1])) # test by reading in the first file and see if it works
head(raw_data)
```

```{r}
for (i in 1:length(files)){ # loop over 1:3 the number of files
}
```

```{r}
for (i in 1:length(files)){ # loop over 1:3 the number of files 
raw_data<-read_csv(paste0(CondPath,"/",files[i]))
glimpse(raw_data)
}
```

```{r}
for (i in 1:length(files)){ # loop over 1:3 the number of files 
raw_data<-read_csv(paste0(CondPath,"/",files[i]))
#glimpse(raw_data)
cond_data$filename[i]<-files[i]
} 
cond_data
```

```{r}
for (i in 1:length(files)){ # loop over 1:3 the number of files 
raw_data<-read_csv(paste0(CondPath,"/",files[i]))
#glimpse(raw_data)
cond_data$filename[i]<-files[i]
cond_data$mean_temp[i]<-mean(raw_data$Temperature, na.rm =TRUE)
cond_data$mean_sal[i]<-mean(raw_data$Salinity, na.rm =TRUE)
} 
cond_data
```

# These next three codes in tidyverse do the exact same thing, just coding it differently
```{r}
1:10 %>% # a vector from 1 to 10 (we are going to do this 10 times) %>% # the vector to iterate over
  map(rnorm, n = 15) %>% # calculate 15 random numbers based on a normal distribution in a list  #This function already exists in your previous code.
  map_dbl(mean)
```

```{r}
1:10 %>% # list 1:10
  map(function(x) rnorm(15, x)) %>% # make your own function within it (used if you have not made the function in your code previously)
  map_dbl(mean)
```

```{r}
1:10 %>%
  map(~ rnorm(15, .x)) %>% # changes the arguments inside the function
  map_dbl(mean)
```

# Saving the data onto computer
```{r}
# point to the location on the computer of the folder
CondPath<-here("Week_12", "data", "cond_data") # telling it where the data is. 
files <- dir(path = CondPath,pattern = ".csv") # list all the data folder with this file path. 

files
```


```{r}
files <- dir(path = CondPath,pattern = ".csv", full.names = TRUE) # this allows us to see the whole file name with pathway SHOWS the entire path name
files
```

```{r}
data<-files %>%
  set_names()%>% # set's the id of each list to the file name
  map_df(read_csv,.id = "filename")%>% # map everything to a dataframe and put the id in a column called filename
  group_by(filename) %>%
  summarise(mean_temp = mean(Temperature, na.rm = TRUE),
            mean_sal = mean(Salinity,na.rm = TRUE))
data
```

