---
title: "FactorsPractice"
author: "Sandy Illescas"
date: "2023-04-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(here)
library(tidyverse)

```

```{r}
income_mean <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-02-09/income_mean.csv')
```
```{r}
fruits<-factor(c("Apple", "Grape", "Banana"))
fruits
```
```{r}
test<-c("A", "1", "2")
as.numeric(test)
```
```{r}
test<-factor(test) # covert to factor
as.numeric(test)

##This assigns numbers to values. Letters always come after numbers.  In this case "A" is assigned "3" because it comes after numbers. 

```


```{r}
glimpse(starwars)
```


```{r}
starwars %>% 
  filter(!is.na(species)) %>% # remove the NAs
  count(species, sort = TRUE)

```
```{r}
star_counts<-starwars %>%
  filter(!is.na(species)) %>%
  mutate(species = fct_lump(species, n = 3)) %>%
  count(species)
star_counts

## This can allowyou to look at a dominant species. the n=3 tells it that unless there are instances where there are 3 or more of the same species present.

## If we were to keep count(species, sort = TRUE), this would sort according to "n"

```

```{r}
star_counts %>%
  ggplot(aes(x = species, y = n))+
  geom_col()
```

```{r}
star_counts %>%
  ggplot(aes(x = fct_reorder(species, n), y = n))+ # allows to sort factors from lowest to smallest, first it sorts by species and then by lowest to give us ascending order. 
  geom_col()
```
```{r}
star_counts %>%
  ggplot(aes(x = fct_reorder(species, n, .desc = TRUE), y = n))+ # This does the same thing, but by adding ".desc = TRUE" allows for a descending order.
  geom_col() +
  labs(x = "Species")
```

```{r}
glimpse(income_mean)
```

```{r}
total_income<-income_mean %>%
  group_by(year, income_quintile)%>%
  summarise(income_dollars_sum = sum(income_dollars))%>% # we are summing all of the values in income_dollars column. 
  mutate(income_quintile = factor(income_quintile)) # changes something in the column, we must ALWAYS mutate it. 

```

```{r}
total_income%>%
ggplot(aes(x = year, y = income_dollars_sum, color = income_quintile))+
  geom_line()
```

```{r}
total_income%>%
  ggplot(aes(x = year, y = income_dollars_sum, 
             color = fct_reorder2(income_quintile,year,income_dollars_sum)))+
  geom_line()+
  labs(color = "income quantile")
```

```{r}
x1 <- factor(c("Jan", "Mar", "Apr", "Dec"))
x1

## When calling 
```

```{r}
x1 <- factor(c("Jan", "Mar", "Apr", "Dec"), levels = c("Jan", "Mar", "Apr", "Dec"))
x1

## levels allows you to choose the specific order your data should be shown. 
```

```{r}
starwars_clean<-starwars %>% 
  filter(!is.na(species)) %>% # removes all N/A species
  count(species, sort = TRUE) %>%
  mutate(species = factor(species)) %>% # makes the species a factor
  filter(n>3) # only keeps species that have more than 3 in the data set
starwars_clean
```

```{r}
levels(starwars_clean$species)
```

```{r}
starwars_clean<-starwars %>% 
  filter(!is.na(species)) %>% # remove the NAs
  count(species, sort = TRUE) %>%
  mutate(species = factor(species)) %>% # make species a factor 
  filter(n>3)  %>% # only keep species that have more than 3 
  droplevels() # drop extra levels

levels(starwars_clean$species)
  
```

```{r}
starwars_clean<-starwars %>% 
  filter(!is.na(species)) %>% # remove the NAs
  count(species, sort = TRUE) %>%
  mutate(species = factor(species)) %>% # make species a factor 
  filter(n>3)  %>% # only keep species that have more than 3 
  droplevels() %>% # drop extra levels 
  mutate(species = fct_recode(species, "Humanoid" = "Human")) # "Humanoid is the new name of the "Human" Column. 
starwars_clean
```



# Loading and Practicing Generating Music
```{r}
library(gm)
m <- 
  Music() +  # initialize a Music object
  Meter(4, 4) + # add a 4/4 time signature
  Line(list("C5", "D5", "E5", "F5"), list(1, 1, 1, 1)) # add a musical line of four quarter notes
show(m, to = c("score", "audio"))
```


