---
title: "Penguin Script"
author: "Sandy Illescas"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
    theme: darkly
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE)

# Only put comments in the chunks, not in text otherwise it sees it as a header, such as below.
```

# Introduction

Today we are going to work with the penguin data to learn *RMarkdown*

# Load Libraries
```{r}
library(here)
library(tidyverse)
library(palmerpenguins)
```

# Inspect the Data
```{r}
glimpse(penguins)
```

# Make a Plot  

Plot the penguin data with bill length by bill depth.
```{r}
penguins %>%  #using the penguin dataset
  ggplot(aes(x = bill_length_mm,
             y = bill_depth_mm,
             color = species)) +
  geom_point() +
  geom_smooth(method = "lm") + #add a linear regression
  labs(x = "Bill Length (mm)", 
       y = "Bill Depth (mm)", 
       color = "SPECIES") +
  theme_bw()
```


```{r}

```

